### ISSUE TITLE
Plugin 0.3.4 joint compilation works on OS X, fails on Windows 8.1

### ISSUE THREAD

**Issue by jkwuc89** [groovy/groovy-android-gradle-plugin#29]
Inside my Android project with mixed Java and Groovy source with all source under src/main/groovy and src/androidTest/groovy, a clean build under OS X works correctly. No errors are reported. The exact same project when built on Windows 8.1 fails with 34 errors. A sampling of the errors that repeat multiple times are below:
CrownAlertDialog.java:80: error: cannot find symbol Constants (Constants is a Groovy file)
error: cannot find symbol com.crown.ivhm.R
error: package R does not exist

**Comment by dovd** [comment]
I'm having the same exact problem: mixed Java and Groovy sources under src/main/groovy builds fine on OS X. But on Windows 8.1 all references from Java to Groovy cause errors:
error: cannot find symbol Centers
...

**Comment by melix** [comment]
I'm closing this after merging #35.
